apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-{{.Values.Service.Name}} #my-service
spec:
  type: NodePort
  selector:
    app: bookstore-api-server
  ports:
    - port: {{.Values.Service.ServicePort}} #8081
      targetPort: {{ .Values.Service.ContainerPort }} #8081
      nodePort: 30007